FROM apache/impala:4.4.1-impala_quickstart_hms
ADD --chown=hive:hive https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.4/hadoop-aws-3.2.4.jar /opt/hive/lib/hadoop-aws-3.2.4.jar
ADD --chown=hive:hive https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar /opt/hive/lib/aws-java-sdk-bundle-1.11.901.jar
